// Generated by scripts/build-menu.js from the De Hawker's Liverpool Uber Eats menu.
export const DRINK_FLAVOURS: Record<string, string[]> = {
  "a2dff4c3-dc1b-4f12-91ce-579caf0d61f6": [
    "Coke",
    "Coke Zero",
    "Fanta"
  ],
  "d9dd26f1-a86a-4301-a2b4-13b2bbf3a975": [
    "Coke",
    "Coke Zero",
    "Vanilla Coke",
    "Fanta",
    "Sprite"
  ]
}
