// One-off data-migration script: combines the De Hawker's Liverpool Uber Eats
// menu (scraped name/description/price/image) with the real customization
// groups (scraped from Uber Eats' internal getMenuItemV1 API) into this
// project's menu.json / itemOptions.ts / drinkFlavours.ts shape.
// Source data: scripts/source-data/uber-eats-{base,customizations}.json
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const customizations = JSON.parse(fs.readFileSync(path.join(__dirname, 'source-data/uber-eats-customizations.json'), 'utf8'));
const base = JSON.parse(fs.readFileSync(path.join(__dirname, 'source-data/uber-eats-base.json'), 'utf8'));

const CATEGORY_ORDER = [
  'Offers', 'Entree', 'Chinese Stir Fried', 'Stir Fried Noodles', 'Noodle Soup',
  'Fried Rice', "Chief's Special", 'Sides', 'Beverage', 'Soup',
];

function baseLookup(category, title) {
  if (category === 'Sides' && title === 'Fried Rice') return base['Fried Rice (Sides)'];
  return base[title];
}

const newUuid = () => crypto.randomUUID();
const dollars = (cents) => Math.round(cents) / 100;

const categories = CATEGORY_ORDER.map((catName) => ({ name: catName, slug: slugify(catName), items: [] }));
const byCatName = new Map(categories.map((c) => [c.name, c]));

const itemOptions = {}; // uuid -> OptionGroup[]
const drinkFlavours = {}; // uuid -> string[]

function slugify(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

for (const entry of customizations) {
  const meta = baseLookup(entry.category, entry.title);
  if (!meta) throw new Error(`No base data for "${entry.category}" / "${entry.title}"`);

  const uuid = newUuid();
  const groups = [];

  for (const group of entry.customizationsList) {
    if (group.title === 'Choice of Flavour') {
      drinkFlavours[uuid] = group.options.map((o) => o.title);
      continue;
    }
    groups.push({
      id: slugify(group.title),
      label: group.title.toUpperCase(),
      required: group.minPermitted >= 1,
      multiSelect: group.maxPermitted > 1,
      choices: group.options.map((o) => ({ label: o.title, priceCents: o.price })),
    });
  }

  if (groups.length > 0) itemOptions[uuid] = groups;

  const cat = byCatName.get(entry.category);
  cat.items.push({
    uuid,
    name: entry.title,
    description: meta.description,
    price: dollars(entry.basePrice),
    imageUrl: meta.imageUrl,
    hasAddons: groups.length > 0,
  });
}

const menuJson = {
  categories: categories.map((c) => ({ name: c.name, slug: c.slug, hasAddons: c.items.some((i) => i.hasAddons), items: c.items })),
  soldOut: [],
  overrides: {},
};

fs.writeFileSync(path.join(ROOT, 'src/data/menu.json'), JSON.stringify(menuJson));

// --- itemOptions.ts -----------------------------------------------------
const itemOptionsLines = [
  "export interface OptionChoice {",
  "  label: string",
  "  priceCents: number",
  "}",
  "",
  "export interface OptionGroup {",
  "  id: string",
  "  label: string",
  "  required: boolean",
  "  multiSelect: boolean",
  "  choices: OptionChoice[]",
  "}",
  "",
  "// Generated by scripts/build-menu.js from the De Hawker's Liverpool Uber Eats menu.",
  "export const ITEM_OPTIONS: Record<string, OptionGroup[]> = {",
];
for (const [uuid, groups] of Object.entries(itemOptions)) {
  itemOptionsLines.push(`  '${uuid}': ${JSON.stringify(groups)},`);
}
itemOptionsLines.push('}', '');
fs.writeFileSync(path.join(ROOT, 'src/lib/itemOptions.ts'), itemOptionsLines.join('\n'));

// --- drinkFlavours.ts -----------------------------------------------------
const drinkFlavoursSrc = [
  "// Generated by scripts/build-menu.js from the De Hawker's Liverpool Uber Eats menu.",
  `export const DRINK_FLAVOURS: Record<string, string[]> = ${JSON.stringify(drinkFlavours, null, 2)}`,
  '',
].join('\n');
fs.writeFileSync(path.join(ROOT, 'src/lib/drinkFlavours.ts'), drinkFlavoursSrc);

const totalItems = categories.reduce((sum, c) => sum + c.items.length, 0);
console.log(`Wrote ${totalItems} items across ${categories.length} categories.`);
console.log(`ITEM_OPTIONS entries: ${Object.keys(itemOptions).length}`);
console.log(`DRINK_FLAVOURS entries: ${Object.keys(drinkFlavours).length}`);
